server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/photoshare?useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: "@Photoshare666"
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  http:
   multipart:
     max-file-size: 10MB
     max-request-size: 30MB
     enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 180


logging:
  level:
   com.cust.dao: debug
   org.springframework.web: info

mybatis:
  mapper-locations: classpath:mybatis/*.xml






